# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x07\n\x05\x45mpty\"\x14\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t2_\n\x0b\x42ookService\x12\'\n\nCreateBook\x12\n.book.Book\x1a\x0b.book.Empty\"\x00\x12\'\n\x08NewBooks\x12\x0b.book.Empty\x1a\n.book.Book\"\x00\x30\x01\x42\x14\n\x12ru.otus.grpc.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022ru.otus.grpc.proto'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_BOOK']._serialized_start=29
  _globals['_BOOK']._serialized_end=49
  _globals['_BOOKSERVICE']._serialized_start=51
  _globals['_BOOKSERVICE']._serialized_end=146
# @@protoc_insertion_point(module_scope)
